export { getStaticPaths, getStaticProps } from '../../ssr/services'

import Head from "next/head";
import styled from "styled-components";
import AdditionalInfo from "../../components/AdditionalInfo";
import ContactStrip from "../../components/ContactStrip";
import CustomSection from "../../components/CustomSection";
import Button from "../../containers/Button";

export default function Service({service}) {
  return (
    <>
      <Head>
        <title>Estetika Dent - Services & Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CustomSection
        title={service?.title}
        desc={service?.desc}
        img={service?.img}
        dir="left"
      >
        <Button>Bukiraj online</Button>
      </CustomSection>

        {service.additional_info &&
            <AdditionalSection>
            {
                service?.additional_info.map(info=>(
                    <AdditionalInfo list={info?.list} title={info.title} desc={info.body}/>
                ))
            }
            </AdditionalSection>
        }
      <ContactStrip text="Imate pitanja? Kontaktirajte nas" />
    </>
  );
}

const AdditionalSection = styled.section`
  background: ${({ theme }) => theme.beige};
  padding:5rem;

  @media(max-width:${({theme})=>theme.tablet}){
    padding:3rem 0;
  }
` 
