import Head from "next/head";
import Hero from "../components/Hero";
import Team from "../components/Team";
import ContactStrip from "../components/ContactStrip";
import CustomSection from "../components/CustomSection";
import Accomodation from "../components/Accomodation";
import Button from "../containers/Button";

import { members, comfort } from "../data";

export default function About() {
  return (
    <>
      <Head>
        <title>Dental Estetica - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title="Stomatološka ordinacija Estetika Dent"
        img="/images/about-hero-bg.png"
      >
        <Button>Bukiraj online</Button>
      </Hero>

      <Accomodation accomodations={comfort} size="small">
        <h1>Vrhunski komfort</h1>
      </Accomodation>

      <CustomSection
        title="Estetika Dent Derventa"
        desc="Lug BB , magistralni put Derventa-Prnjavor, 100m poslije Doma za stara lica-Zlatni lug, sa desne strane Derventa, 74 400 Bosnia and Herzegovina"
        img="/images/about-estetika-section.png"
      >
        <Button>Bukiraj online</Button>
      </CustomSection>

      <CustomSection
        title="Estetika Dent Gradačac"
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
        img="/images/about-estetik2-section.png"
        dir="left"
      >
        <Button>Bukiraj online</Button>
      </CustomSection>

      <Team members={members} title="Naše osoblje" />

      <ContactStrip text="Imate pitanja? Kontaktirajte nas" />
    </>
  );
}
