import Head from "next/head";
import Hero from "../components/Hero";
import Team from "../components/Team";
import ContactStrip from "../components/ContactStrip";
import CustomSection from "../components/CustomSection";
import Accomodation from "../components/Accomodation";
import Button from "../containers/Button";

import { members, accomodations } from "../data";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title="Odlazak zubaru po evropskim standardima"
        img="/images/mature-lady-showing-theets.png"
      >
        <Button>Bukiraj online</Button>
      </Hero>

      <Accomodation accomodations={accomodations}>
        <h1>Vrhunski komfort</h1>
      </Accomodation>

      <CustomSection
        title="Lokacija 1"
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
        img="/images/about-img-1.png"
      >
        <Button>Bukiraj online</Button>
      </CustomSection>

      <CustomSection
        title="Lokacija 2"
        desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
        img="/images/about-img-2.png"
        dir="left"
      >
        <Button>Bukiraj online</Button>
      </CustomSection>

      <Team members={members} title="Vrhunski strucnjaci" />

      <ContactStrip text="Imate pitanja? Kontaktirajte nas" />
    </>
  );
}
